security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_MEMBER:       ROLE_MEMBER
        ROLE_ARTISAN:       ROLE_ARTISAN
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                default_target_path: redirecttohome
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            oauth:
              resource_owners:
                facebook: "/connect/check-facebook"
                google:   "/connect/check_google"
              login_path: /connect
              failure_path: /connect

              oauth_user_provider:
                service: hwi_oauth.user.provider.fosub_bridge



            logout:
                target: /

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }