<?php

namespace MainBundle\Repository;

/**
 * PubgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubgRepository extends \Doctrine\ORM\EntityRepository
{
}
