<?php

namespace ProduitBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends EntityRepository
{
    public function avgrating()
    {
        $query = $this->getEntityManager()->createQuery(
            "SELECT c.idE , AVG(c.rating) AS avgrating FROM ProduitBundle:Avis c
             GROUP BY c.idE  "
        );
        return $query->getResult();

    }
}
