<?php
/**
 * Created by PhpStorm.
 * User: jskka
 * Date: 05/04/2018
 * Time: 18:59
 */

namespace ProduitBundle\Repository;

/**
 * ProduitpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitpRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $titre
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findByName(string  $titre){
       return $qb = $this->createQueryBuilder('n')
            ->select('p')
            ->where('p.titre LIKE %' . $titre . '%');
    }

}