main_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
contact:
    path:     /contact
    defaults: { _controller: MainBundle:Default:contact }
about:
    path:     /about
    defaults: { _controller: MainBundle:Default:about }

